In [138]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

In [139]:
df = pd.read_csv('F1_2122.csv')
df.dropna(inplace=True)
df.head(10)

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,F1,06/08/2021,20:00,Monaco,Nantes,1,1,D,1,1,...,2.02,-1.25,2.02,1.91,2.02,1.91,2.03,1.99,1.97,1.89
1,F1,07/08/2021,16:00,Lyon,Brest,1,1,D,0,1,...,2.76,-1.50,2.00,1.93,2.00,1.93,2.00,1.94,1.96,1.89
2,F1,07/08/2021,20:00,Troyes,Paris SG,1,2,A,1,2,...,2.35,1.50,1.95,1.98,1.93,2.00,2.04,2.00,1.91,1.95
3,F1,08/08/2021,12:00,Rennes,Lens,1,1,D,1,1,...,1.82,-0.50,1.93,2.00,1.93,2.00,1.94,2.00,1.91,1.95
4,F1,08/08/2021,14:00,Bordeaux,Clermont,0,2,A,0,0,...,1.69,0.00,1.87,2.06,1.88,2.06,1.89,2.10,1.84,2.03
5,F1,08/08/2021,14:00,Nice,Reims,0,0,D,0,0,...,1.64,-0.50,1.83,2.10,1.81,2.12,1.84,2.13,1.81,2.05
6,F1,08/08/2021,14:00,St Etienne,Lorient,1,1,D,0,0,...,1.72,-0.25,1.91,2.02,1.90,2.02,1.91,2.03,1.88,1.98
7,F1,08/08/2021,14:00,Strasbourg,Angers,0,2,A,0,0,...,1.72,-0.50,2.07,1.86,2.08,1.85,2.10,1.87,2.05,1.82
8,F1,08/08/2021,16:00,Metz,Lille,3,3,D,2,1,...,1.52,0.50,2.10,1.83,2.10,1.84,2.10,1.90,2.02,1.84
9,F1,08/08/2021,19:45,Montpellier,Marseille,2,3,A,2,0,...,2.05,0.50,1.84,2.09,1.85,2.09,1.85,2.10,1.80,2.07

In [140]:
df_equipe = df[['HomeTeam', 'AwayTeam', 'FTR']]
df_equipe['FTR'] = df_equipe['FTR'].replace(['H', 'D', 'A'], [1, 0, 2])
#df_equipe.head(10)

/var/folders/bg/vbvjjnmj0hv9wmb92ngxcq9m0000gn/T/ipykernel_1162/1141455902.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_equipe['FTR'] = df_equipe['FTR'].replace(['H', 'D', 'A'], [1, 0, 2])

In [141]:
df = df.drop(['Div', 'Date', 'Time', 'HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'FTR', 'HTHG', 'HTAG', 'HTR', 'HS', 'AS', 'HST', 'AST', 'HF', 'AF', 'HC', 'AC', 'HY', 'AY', 'HR', 'AR'], axis=1)
#df.head()

In [142]:
X = df
y = df_equipe['FTR']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

clf = DecisionTreeClassifier()
clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)

accuracy = clf.score(X_test, y_test)
print("Accuracy:", accuracy)

Accuracy: 0.41333333333333333

In [143]:
df_final = pd.DataFrame()
df_final['RÃ©sultat'] = y_test
df_final['PrÃ©diction'] = y_pred

In [144]:
#merged_df = pd.merge(df_equipe[['HomeTeam', 'AwayTeam']], df_final, on='id')
df_final = pd.merge(df_equipe[['HomeTeam', 'AwayTeam']].reset_index(), df_final.reset_index(), on='index')
df_final

    index     HomeTeam    AwayTeam  RÃ©sultat  PrÃ©diction
0       0       Monaco      Nantes         0           1
1       3       Rennes        Lens         0           2
2       5         Nice       Reims         0           1
3       9  Montpellier   Marseille         2           2
4      15     Clermont      Troyes         1           2
..    ...          ...         ...       ...         ...
70    355        Reims        Lens         2           2
71    359       Nantes      Rennes         1           1
72    361         Lyon      Nantes         1           2
73    367   St Etienne       Reims         2           2
74    376    Marseille  Strasbourg         1           2

[75 rows x 5 columns]